version: '3'
services:
  app:
    image: your-dockerhub-username/Gregslist_the_last_dance:latest
    restart: unless-stopped
    env_file:
      - Gregslist_the_last_dance-env
    ports:
      - "7045:80"
